export 'package:widget_formato/presentation/screens/animated/animated_screen.dart';
export 'package:widget_formato/presentation/screens/app_tutorial_screen/app_tutorial_screen.dart';
export 'package:widget_formato/presentation/screens/buttons/buttons_screen.dart';
export 'package:widget_formato/presentation/screens/cards/cards_screen.dart';
export 'package:widget_formato/presentation/screens/home/home_screen.dart';
export 'package:widget_formato/presentation/screens/infinite_scroll/infinite_scroll.dart';
export 'package:widget_formato/presentation/screens/progress/progress_screen.dart';
export 'package:widget_formato/presentation/screens/snackbar/snackbar_screen.dart';
export 'package:widget_formato/presentation/screens/ui_controls/ui_controls_screen.dart';